### PR TITLE
Update test

### PR DESCRIPTION
**Pull request by teunbrand**
Hi folks,

Apologies for the cold PR without posting an issue first.
The ggplot2 package has rewritten the guide system and, as a result, one of the test expectations no longer hold in combination with development version of ggplot2.
This PR updates that test to be compatible with both the current and development version of ggplot2.

Best,
Teun

### CODE REVIEW

**Comment by lcougnaud** [comment]
Thanks for the PR!
When will the ggplot2 update be available in CRAN?
The previous test seems to work with the current version ggplot2 (4.4.3) in CRAN.

**Comment by teunbrand** [comment]
Yes, the current tests will work fine as-is until the guide rewrite that is in the development version will be on CRAN.
When that will happen is still unclear, but probably in a month or two. This PR is just a proposal for an updated test, so that when the new version lands on CRAN, inTextSummaryTable's tests will not start failing immediately.

**Comment by teunbrand** [comment]
Hi there,

I've updated this PR to reflect that latest changes in ggplot2 and the master branch.
The only change that was required is that one plot is no longer silent, which is intentional from ggplot2's side.
I'm testing instead whether the code delivers a ggplot object.

To test the code changes with the release candidate, you can install it with the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The release of ggplot2 3.5.0 is scheduled for the 12th of February. The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588. We hope that this PR might help inTextSummaryTable get out a fix if necessary.

**Comment by teunbrand** [comment]
This is just a kind reminder that the release is scheduled soon.

**Comment by lcougnaud** [comment]
Thanks for the notification & for the hints!
A new version of the package, including these fixes, will be released to CRAN soon.

**Pull request closed without merging**
